### ISSUE TITLE
BUILD_SSL - https for windows - null pointer when "SocketImpl::set_keep_alive"

### ISSUE THREAD

**Issue by linfengca** [Corvusoft/restbed#463] opened 2021-02-26 10:06 UTC
void SocketImpl::set_keep_alive( const uint32_t start, const uint32_t interval, const uint32_t cnt)
        {
            (void) cnt;
            (void) start;
            (void) interval;
#ifdef _WIN32
            std::string val = "1";
            **_setsockopt(m_socket->native_handle(), SOL_SOCKET, SO_KEEPALIVE, val.c_str(), sizeof(val));_**

**when a https restful request is comming, m_socket is empty, then exception!!**

call stack:
 	restbed-shared.dll!asio::basic_io_object<asio::detail::win_iocp_socket_service<asio::ip::tcp>,1>::get_service() 行 259	C++
 	restbed-shared.dll!asio::basic_socket<asio::ip::tcp>::native_handle() 行 511	C++
>	restbed-shared.dll!restbed::detail::SocketImpl::set_keep_alive(const unsigned int start, const unsigned int interval, const unsigned int cnt) 行 273	C++
 	restbed-shared.dll!restbed::detail::ServiceImpl::create_ssl_session::__l5::<lambda>(const std::error_code & error) 行 300	C++
 	restbed-shared.dll!asio::ssl::detail::handshake_op::call_handler<void <lambda>(const std::error_code &) >(restbed::detail::ServiceImpl::create_ssl_session::__l5::void <lambda>(const std::error_code &) & handler, const std::error_code & ec, const unsigned int & __formal) 行 50	C++
 	restbed-shared.dll!asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) >::operator()(std::error_code ec, unsigned int bytes_transferred, int start) 行 266	C++
 	restbed-shared.dll!asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >::operator()(const std::error_code & ec, unsigned int bytes_transferred, int start) 行 269	C++
 	restbed-shared.dll!asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int>::operator()() 行 165	C++
 	restbed-shared.dll!asio::asio_handler_invoke<asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int> >(asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int> & function, ...) 行 69	C++
 	restbed-shared.dll!asio_handler_invoke_helpers::invoke<asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int>,void <lambda>(const std::error_code &) >(asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int> & function, restbed::detail::ServiceImpl::create_ssl_session::__l5::void <lambda>(const std::error_code &) & context) 行 37	C++
 	restbed-shared.dll!asio::ssl::detail::asio_handler_invoke<asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int>,asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) >(asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int> & function, asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > * this_handler) 行 315	C++
 	restbed-shared.dll!asio_handler_invoke_helpers::invoke<asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int>,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >(asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int> & function, asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > & context) 行 37	C++
 	restbed-shared.dll!asio::detail::asio_handler_invoke<asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int>,asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >(asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int> & function, asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > > * this_handler) 行 320	C++
 	restbed-shared.dll!asio_handler_invoke_helpers::invoke<asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int>,asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > > >(asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int> & function, asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > > & context) 行 37	C++
 	restbed-shared.dll!asio::detail::handler_work<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,asio::system_executor>::complete<asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int> >(asio::detail::binder2<asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > >,std::error_code,unsigned int> & function, asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > > & handler) 行 81	C++
 	restbed-shared.dll!asio::detail::win_iocp_socket_send_op<asio::const_buffers_1,asio::detail::write_op<asio::basic_stream_socket<asio::ip::tcp>,asio::mutable_buffer,asio::mutable_buffer const *,asio::detail::transfer_all_t,asio::ssl::detail::io_op<asio::basic_stream_socket<asio::ip::tcp>,asio::ssl::detail::handshake_op,void <lambda>(const std::error_code &) > > >::do_complete(void * owner, asio::detail::win_iocp_operation * base, const std::error_code & result_ec, unsigned int bytes_transferred) 行 95	C++
 	restbed-shared.dll!asio::detail::win_iocp_operation::complete(void * owner, const std::error_code & ec, unsigned int bytes_transferred) 行 46	C++
 	restbed-shared.dll!asio::detail::win_iocp_io_context::do_one(unsigned long msec, std::error_code & ec) 行 420	C++
 	restbed-shared.dll!asio::detail::win_iocp_io_context::run(std::error_code & ec) 行 162	C++
 	restbed-shared.dll!asio::io_context::run() 行 61	C++
 	restbed-shared.dll!restbed::Service::start(const std::shared_ptr<restbed::Settings const > & settings) 行 192	C++
 	main(const int __formal, const char * * __formal)

**Comment by gma-work** [comment] 2021-04-22 12:55
This seems to be a duplicate of issue #440, which has a couple of possible solutions in the comments.

**Comment by ben-crowhurst** [comment] 2021-06-08 07:29
This issue will be resolved with https://github.com/Corvusoft/restbed/issues/440.

**Closed by ben-crowhurst** 2021-06-08 07:29 UTC
Labels: bug, duplicate
