### ISSUE TITLE
Cannot compile restbed

### ISSUE THREAD

**Issue by hoang408** [Corvusoft/restbed#325] opened 2018-07-11 06:43 UTC
I am trying to install restbed on Ubuntu 18.04, and use this [post](https://github.com/Corvusoft/restbed/issues/238)<a href="post"></a> to help me with the installation.  I add `-lpthread` and get this command:

cmake [-DBUILD_TESTS=YES] [-DBUILD_EXAMPLES=YES] [-DBUILD_SSL=NO] [-DBUILD_SHARED=YES] [-DCMAKE_INSTALL_PREFIX=/output-directory] -lpthread ..

Next, I execute `make install`.  It fails with this error:

    /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
    (.text+0x11): undefined reference to `dlopen'
    (.text+0x24): undefined reference to `dlsym'
    (.text+0x2f): undefined reference to `dlclose'
    /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
    (.text+0x1c4): undefined reference to `dlsym'
    (.text+0x282): undefined reference to `dlerror'
    /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
    (.text+0x2e8): undefined reference to `dlopen'
    (.text+0x359): undefined reference to `dlclose'
    (.text+0x395): undefined reference to `dlerror'
    /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
    (.text+0x461): undefined reference to `dladdr'
    (.text+0x4c6): undefined reference to `dlerror'
    /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
    (.text+0x6a2): undefined reference to `dlclose'
    collect2: error: ld returned 1 exit status
    test/unit/CMakeFiles/service_unit_test_suite.dir/build.make:86: recipe for target 'test/unit/service_unit_test_suite' failed
    make[2]: *** [test/unit/service_unit_test_suite] Error 1
    CMakeFiles/Makefile2:182: recipe for target 'test/unit/CMakeFiles/service_unit_test_suite.dir/all' failed
    make[1]: *** [test/unit/CMakeFiles/service_unit_test_suite.dir/all] Error 2
    Makefile:140: recipe for target 'all' failed
    make: *** [all] Error 2

Could someone tell me what I get wrong?  Thanks.

**Comment by ben-crowhurst** [comment] 2018-07-23 09:16
As @AmarOk1412  has suggested OpenSSL.  Please build as per the instructions.

**Comment by jelmew** [comment] 2018-07-31 13:57
I also get the same error on fedora while following the instructions to the letters.

**Comment by ben-crowhurst** [comment] 2020-02-08 03:28
Closing as duplicate of #312 (comment). This will be addressed in 4.7 release.

**Closed by ben-crowhurst** 2020-02-08 03:28 UTC
