### ISSUE TITLE
service_error_handler 400 - End of file

### ISSUE THREAD

**Issue by fxfire** [Corvusoft/restbed#399] opened 2019-12-18 09:55 UTC
Hi,
I'm sorry in advance, this is probably a silly question. I am getting quite often this error, which is thrown in the restbed::Service->set_error_handler function. 
All I see is error num 400, and the exception.what() is "End of file".
From peeking into the source, it comes from asio, but I am not sure if this is a result of bad coding on my side or just a normal handled asio error that can happen when for ex. the session is fetched and the client connection is interrupted or other 'normal' cases.
I tried google, but could not find anything useful on it. Maybe someone can give me a hint :) ?
Thanks!

**Comment by ben-crowhurst** [comment] 2020-01-08 08:11
Please provide some code to debug your issue.

**Comment by fxfire** [comment] 2020-01-09 11:02
That is sadly the issue, I have too much code already and cannot pinpoint down the location of it. 
The handled exception / error comes up only like once every 10 min, while around 2000+ connections are made from all over the globe to the server in that time. (very nice work on that project btw, it runs under 3% CPU on a 4 core VM 👍 )

This is the callstack, when the error is thrown:
[callstack.txt](https://github.com/Corvusoft/restbed/files/4040027/callstack.txt)

**Comment by ben-crowhurst** [comment] 2020-02-03 01:43
Could you attempt to write up a smaller example using restbed and replicate the issue? Once we have something to work off we can investigate the problem.

**Comment by ben-crowhurst** [comment] 2020-02-08 01:55
No user example supplied, closing.  Please reopen if you find the cause of this issue to be with the framework and supplied a failing example.

Thanks.

**Closed by ben-crowhurst** 2020-02-08 01:55 UTC
Labels: help wanted

**Comment by stan-yu** [comment] 2025-05-13 09:37
Hi,
I have the same error with number 400, and exception.what() is "End of file" in custom error_handler.
To reproduce this error, I took your example documentation/example/HTTP_PIPELINING.md and modified it slightly in the error handler part:

```
void error_handler(const int status_code, const exception& error, const shared_ptr<Session>& session) { /* here error is made a constant reference */
  fprintf(stderr, "status: %d, er: %s", status_code, error.what()); // added error output
  if (session not_eq nullptr and session->is_open()) {
  ...
```
After that, compile and run the example, and send a request to the service:
curl -w'\n' -v --header 'Connection: keep-alive' -X GET 'http://localhost:1984/resource/1'

output on stderr:
status: 400, er: End of file


If do not add a custom error handler (i.e. comment out the line service.set_error_handler(error_handler);), the service does not output any errors.
I have this error reproduced on Ubuntu 22.04 and Oracle Linux 8.10.

Is this expected behavior? Or if the session is closed, this error can be ignored?

Thanks!

**Comment by ben-crowhurst** [comment] 2025-05-19 07:09
@stan-yu, please can you open up a new issue and link the closed ticket?
