### ISSUE TITLE
Example https_client_verify_none returns 400

### ISSUE THREAD

**Issue by xuzhang97** [Corvusoft/restbed#79] opened 2016-03-03 21:28 UTC
The HTTPS client example (https_client_verify_none) does not work at the commit cd0db3c4ca7bb35bf6c7371b3ac53289eb27765e. The service complains about Bad Request.

example/example/https_client_verify_none 
*** Response ***
Status Code:    400
Status Message: Bad Request
HTTP Version:   1.0
HTTP Protocol:  HTTP
Header 'Content-Length' > '1555'
Header 'Content-Type' > 'text/html; charset=UTF-8'
Header 'Date' > 'Thu, 03 Mar 2016 21:26:05 GMT'
Body:           <!D...

**Comment by callum-kirby** [comment] 2016-03-03 21:58
Xu Zhang, I believe this is due to setting the parameter 'query' without first percent encoding its value; causing Google to respond with 400 Bad Request. 

**Offending Code**
```
request->set_query_parameter( "query", "search term" );
```
**Replicate Issue**
```
curl -XGET -v 'https://www.google.co.nz?query=search term'
```

**Resolve Issue**
curl -XGET -v 'https://www.google.co.nz?query=search%20term'

**Fix**
```
request->set_query_parameter( "query", Uri::encode( "search term" ) );
```

I'll make the necessary changes.

**Comment by xuzhang97** [comment] 2016-03-03 22:08
Hi,
    I'd like to add one observation. The issue still exists without setting query parameter. There is NO problem if HTTP is used.

Thanks,

Xu Zhang

**Comment by callum-kirby** [comment] 2016-03-03 22:11
Found the issue. The client code drops in HTTPS/1.1 not HTTP/1.1.
```
GET /?query=search%20term HTTPS/1.1
Accept: */*
Host: www.google.co.nz
```

**Comment by callum-kirby** [comment] 2016-03-03 22:14
Just writing a regression test and then I'll push a fix in the next hour.

**Comment by callum-kirby** [comment] 2016-03-03 22:59
@xuzhang97 We've pushed a fix without the appropriate regression test.

This ticket has raised issues around current development.  Our goal is to allow individuals to violate the HTTP specification if they wish, for testing purposes say.

With the upcoming 4.0 release we'll hard-code a solution into the HTTP implementation and look to have this removed when we start dependency injecting Protocols via ```Service::add_application_layer``` at a later date.

**Example**
```
HTTPApplicationLayer http_application_layer;

Service service;
service.add_application_layer( "^http|https$", http_application_layer );
```

**Closed by callum-kirby** 2016-03-03 22:59 UTC
Labels: bug
