### ISSUE TITLE
Socket reference lost in request with large body data

### ISSUE THREAD

**Issue by SmokeyMcGasso** [Corvusoft/restbed#92] opened 2016-05-03 14:54 UTC
On non-localhost requests with a content-length of >= 1261537 bytes, the session is closed while still fetching data, therefore the fetch callback is never called.

In session.cpp: `void Session::fetch( const size_t length, const function< void ( const shared_ptr< Session >, const Bytes& ) >& callback )`, in de following code block:

`const auto message = String::format( "Fetch failed: %s", error.message( ).data( ) );
                    const auto error_handler = m_pimpl->get_error_handler( );
                    return error_handler( 500, runtime_error( message ), session );`

Message will be 

> Fetch failed: Bad file descriptor

Possibly related to [Issue #59 ](https://github.com/Corvusoft/restbed/issues/59). 
Request headers:
`Accept = "application/json";
    "Accept-Language" = "en;q=1";
    Authorization = d2f6ce85a57458057162579b85ef0b52da45bf9d59ec7b09b1a1c10232fbac20;
    "Content-Type" = "application/json; charset=utf-8";
Content-Length = 1261537;
Connection: keep-alive`

The code seems to work as expected when issuing an identical request over the local loopback interface.

**Comment by ben-crowhurst** [comment] 2016-05-03 20:54
Please can you provide server/client code to replicate this issue.

**Comment by SmokeyMcGasso** [comment] 2016-05-04 21:49
Hi, of course. This is the server code.
```
#include <memory>
#include <cstdlib>
#include <restbed>

using namespace std;
using namespace restbed;

void error_handler (const int statusCode, const exception& exception, const shared_ptr< Session >& session)
{
  fprintf( stdout, "%s\n", exception.what() );
  session->close( statusCode, exception.what(), { { "Server", "Restbed" } } );
}

void post_method_handler( const shared_ptr< Session > session )
{
    const auto request = session->get_request( );

    size_t content_length = 0;
    request->get_header( "Content-Length", content_length );

    session->fetch( content_length, [ request ]( const shared_ptr< Session > session, const Bytes & body )
    {
        fprintf( stdout, "%d\n", ( int ) body.size( ));
        session->close( OK, "Hello, World!", { { "Content-Length", "13" }, { "Connection", "close" } } );
    } );
}

int main( const int, const char** )
{
    auto resource = make_shared< Resource >( );
    resource->set_path( "/resource" );
    resource->set_method_handler( "POST", post_method_handler );

    shared_ptr< Settings > settings = make_shared < Settings >( );
    settings->set_port(1994);

    Service service;
    service.set_error_handler(error_handler);
    service.publish( resource );
    service.start( settings );

    return EXIT_SUCCESS;
}
```

The following code is the HTTP request. The `3mb_request.json` file is a JSON object containing a large Base64 encoded PNG image.

```
curl -H "Content-Type: application/json" \
    -H "Accept: application/json" \
    -H "Connection: keep-alive" \
    --data @3mb_request.json \
    http://addr:1994/resource
```

I was able to replicate the issue on localhost by using a bandwidth limiter on the network interface. Specifically OS X' `Network Link Conditioner` set to the 3G profile (330 kbps uplink).

**Comment by ben-crowhurst** [comment] 2016-06-05 20:47
I'm having trouble replicating this issue.  I've run the [HTTP Service](https://github.com/Corvusoft/restbed/blob/master/example/https_service/source/example.cpp) example and hit the service with Base64 files of 1mb, 3mb, 7mb, and 9mb files with no loss off data; with and without the Network Link Conditioner.

Can you offer me any more information for duplicating your conditions?

**Comment by SmokeyMcGasso** [comment] 2016-06-07 14:48
Hmm, odd. I've tested this on both Ubuntu 14.04 and OSX El Capitan. The problem does seem easier to replicate when performing requests over the internet and when SSL is enabled. The issue always occurs within the session->fetch method after a certain amount of time though.

I could run a script on my server in The Netherlands which will continuously perform POST requests on your server, if this will help. 

I'll try again using the current HEAD revision and get back to you if I can't replicate the issue anymore. Please let me know if there's anything I can do to assist.

**Comment by ben-crowhurst** [comment] 2016-06-08 02:16
I'll set up a rig between London and New Zealand, see if that replicates the issue.

**Comment by ben-crowhurst** [comment] 2016-06-09 21:22
Setup a rig between London and New Zealand with still no luck in replicating this issue.  I've also attempted an alternative [bandwidth limiter](http://slowyapp.com/download) set to 56k for a 12 megabyte file and sadly, still no luck.

**Comment by SmokeyMcGasso** [comment] 2016-06-10 09:46
Alright, thank you for looking into it anyway. Must have something to do with my setup. Any suggestions on where to start debugging?

**Comment by ben-crowhurst** [comment] 2016-06-10 22:26
I'm very keen to resolve this issue, can you share your codebase?

**Comment by SmokeyMcGasso** [comment] 2016-06-16 10:30
Great! Sure, I'm on holiday now but I'll send you a repo invite next week.

**Comment by ben-crowhurst** [comment] 2016-06-17 02:04
Not a problem, enjoy your holiday.

**Comment by SmokeyMcGasso** [comment] 2016-06-22 10:02
I've uploaded my code to GitHub [here](https://github.com/SmokeyMcGasso/mobile-backend-test_restbed). The network-tests directory contains the scripts for testing this issue. As you will see the code is fairly simple, so I doubt that might be the issue. Thanks for your help.

**Comment by ben-crowhurst** [comment] 2016-06-22 20:30
Thanks for hanging in there @SmokeyMcGasso. I'll take a crack at resolving this issue today.

Hope you enjoyed your holiday.

**Comment by ben-crowhurst** [comment] 2016-06-26 10:33
I've managed to cause a segfault however it involves tweaking the client code and shutting down the active socket.  I'll resolve this issue and hope it helps your situation

```
Fetch failed: End of file
Close failed: session already closed.
Close failed: session already closed.
Close failed: session already closed.
Close failed: session already closed.
Close failed: session already closed.
...
Close failed: session already closed.
Close failed: session already closed.
Segmentation fault: 11
```

**Comment by ben-crowhurst** [comment] 2016-06-26 10:35
I'm also not convinced the Network Link Conditioner works on El Captain.

**Comment by ben-crowhurst** [comment] 2016-06-27 04:38
Please update your error handler to the following. Failing to do so causes the stack hammering seen above.

``` C++
void error_handler (const int statusCode, const exception& exception, const shared_ptr< Session >& session)
{
  fprintf( stdout, "%s\n", exception.what() );
  // Place breakpoint here

  if ( session->is_open( ) )
  {
      session->close( statusCode, exception.what(), { { "Server", "Restbed" } } );
  }
}
```

**Comment by ben-crowhurst** [comment] 2016-06-27 04:39
Just an update, I'm still failing to replicate your issue.  I have a few more roads to travel and will keep you informed.

**Comment by SmokeyMcGasso** [comment] 2016-06-27 10:18
Hi Ben, thank you for the update. I've updated my error handler, but unfortunately the issue still persists. Are you able to verify whether the NLC is working on http://www.speedtest.net/? You should be able to see a significant difference in upload and download speed with the profile enabled.

If it's not working, you might be using an old version which came preinstalled with Xcode. More recent versions of Xcode do not install or update the NLC by default. Instead, it needs to be installed separately by downloading the "Hardware IO tools for Xcode" package from the [Apple developer website](https://developer.apple.com/downloads/). I can send you the package if you do not have access to a developer account.

Alternatively, I can write you a simple iOS or Android app to run the tests.

**Comment by ben-crowhurst** [comment] 2016-06-27 10:25
We've access to a developer account. I've attempted the download-redownload trick with little luck. Going down the firewall road to test the setup.

**Comment by kvnnap** [comment] 2016-07-07 17:16
I am also having the same issue. In my case though, it is when I send data bigger than 1404 bytes. The following are snippets of the code. On the client side I have:

```
shared_ptr<Request> request = make_shared<Request>( Uri( string("http://") + restHost + "/my-submit" ) );
request->set_header( "Accept", "application/json" );
request->set_header( "Content-Type", "application/json" );
request->set_header( "Host", restHost );
request->set_method("POST");
string clientBody = ...;
request->set_header("Content-Length", to_string(clientBody.length()));
request->set_body(clientBody);
shared_ptr<Response> response = Http::sync(request);
```

where clientBody.size() is 1405 bytes.

On the server side I have:

```
shared_ptr<Resource> mySubmitResource = make_shared<Resource>();
mySubmitResource->set_path("/my-submit");
mySubmitResource->set_error_handler([](const int code, const exception& ex, const shared_ptr< Session > session) {
    cout << "Internal Error: " << ex.what() << endl;
});
mySubmitResource->set_method_handler("POST", [this](const shared_ptr<Session> session) -> void {
    // Get Request
    const shared_ptr<const Request> request = session->get_request();

    // Get Content Length from Header
    size_t content_length = 0;
    request->get_header("Content-Length", content_length);

    // Get Body Data
    string strBody;
    cout << "Content-length body size: " << content_length << endl;
    session->fetch(content_length, [&strBody]( const shared_ptr< Session > session, const restbed::Bytes & body ){
        cout << "Body Size: " << body.size() << endl;
        strBody = string(reinterpret_cast<const char*>(body.data()), body.size());
    });
    cout << "Received request" << endl;
    ...
}
```

Server output is:
>
Content-length body size: 1405
Received request
Internal Error: Fetch failed: Bad file descriptor
>

strBody.size() is 0

Data less than 1405 bytes works perfectly. I am running the server and the client both on the same machine using the eth0 interface with IP 192.168.134.131.

**Comment by ben-crowhurst** [comment] 2016-07-07 20:29
What OS are you running on?

**Comment by ben-crowhurst** [comment] 2016-07-07 20:32
Please supply the additional code after:

``` C++
    cout << "Received request" << endl;
    ...
```

This might be the causes of the issue as the logic should be inside the fetch handler.

**Comment by kvnnap** [comment] 2016-07-08 07:34
OS is Ubuntu 14.04 - specifically: 
> 
Linux ubuntu 3.19.0-61-generic #69~14.04.1-Ubuntu SMP Thu Jun 9 09:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
> 

I had filtered the code to remove the irrelevant parts, the full code can be accessed [here](https://github.com/kvnnap/mesos-dds/tree/7dbc6cad68fc00e4886e105ccff0e911766d4d90).

The output on the server, coming from the file [Server.cc](https://github.com/kvnnap/mesos-dds/blob/7dbc6cad68fc00e4886e105ccff0e911766d4d90/DDSRestServer/Server.cc#L50) is:
>
Content-length body size: 1405
Received request
{"error":"Exception: JSON in input stream is not in UTF-8."}
Internal Error: Fetch failed: Bad file descriptor
>

While the client output, coming from [DDSPlugin/main.cc](https://github.com/kvnnap/mesos-dds/blob/7dbc6cad68fc00e4886e105ccff0e911766d4d90/DDSPlugin/main.cc#L116) is (filtered):
>
Request Failed - Did not submit: {"error":"Exception: JSON in input stream is not in UTF-8."}
>

The JSON error is coming from the fact that it is being fed an empty string as strBody.size() is 0 since `strBody = string(reinterpret_cast<const char*>(body.data()), body.size());` is never being executed at the server side.

I hope this helps

**Comment by ben-crowhurst** [comment] 2016-07-08 23:40
Fetch is being called out of sequence.  Please try moving your code into the fetch callback handler.

You see the fetch call is Asynchronous, it won't be invoked until the data has been read. You schedule the fetch handler for execution and then proceed directly to [line 82](https://github.com/kvnnap/mesos-dds/blob/7dbc6cad68fc00e4886e105ccff0e911766d4d90/DDSRestServer/Server.cc#L82).

Please try the following:

``` C++
        cout << "Content-length body size: " << content_length << endl;
        
        session->fetch(content_length, [ ]( const shared_ptr< Session > session, const restbed::Bytes & body ){
            cout << "Body Size: " << body.size() << endl;
            auto strBody = restbed::String::to_string( body );

            // Parse Json and get Object
            string sError;
            try
            {
            ...
        });
        cout << "Received request" << endl;
```

This is our mistake for the lack of documentation; an issue which is currently being resolved.

**Comment by ben-crowhurst** [comment] 2016-07-08 23:49
**aside:**  You may, read should, be able to remove the use of threads in the server code by utilising restbed::Service::set_ready_handler feature.  The ready handler will not be invoked until the server is ready to service incoming HTTP requests.  See [Service Ready Handler](https://github.com/Corvusoft/restbed/blob/master/example/service_ready_handler/source/example.cpp), [Schedule Work on Service Runloop](https://github.com/Corvusoft/restbed/blob/master/example/schedule_work_on_service_runloop/source/example.cpp), and [Multi-Threading](https://github.com/Corvusoft/restbed/blob/master/example/multithreaded_service/source/example.cpp) examples for details.

Its best to leave threading to the internal runloop.

**Comment by ben-crowhurst** [comment] 2016-07-12 01:38
Any feedback regarding this issue?

**Comment by kvnnap** [comment] 2016-07-12 07:45
Hi, sorry for the late reply. 

Indeed, fetch is asynchronous and despite the lack of documentation, my lack of experience with asynchronous methods in C++ is also to blame and I could have easily checked the thread ID's to verify that fetch is asynchronous. I had also mixed up the fetch method in this code with the fetch method [here](https://github.com/Corvusoft/restbed/blob/master/example/http_client/source/example.cpp#L33), thinking the former had to be synchronous as well. 

As I thought this was a bug and did not have much time left, I switched to Microsoft Casablanca. This morning I rolled back to the previous version so that I can give you feedback with regards to your suggestion of moving the code to the fetch callback handler. However, it seems that a recent change [here](https://github.com/Corvusoft/restbed/blob/07bc5d0bc403800066b88c5ba3fa28907e688960/source/corvusoft/restbed/request.hpp#L18) gives this error:
>
fatal error: corvusoft/restbed/detail/common_impl.hpp: No such file or directory
 #include \<corvusoft/restbed/detail/common_impl.hpp\>
>

When I run `make install`, the detail directory is indeed missing.

Let me know whether this is another issue or whether I am doing something wrong, so that I can give you feedback with regards to this issue.

**Comment by ben-crowhurst** [comment] 2016-07-12 09:47
@kvnnap Can i know your configuration? OS, Compliler? STL?

**Comment by kvnnap** [comment] 2016-07-12 10:13
@ben-crowhurst 
- OS: Ubuntu 14.04
- Compiler: g++ (Ubuntu 6.1.1-3ubuntu11~14.04.1) 6.1.1 20160511
- Linking to libstdc++.so.6

And what I mean is that when I compile restbed and do `make install` I get the following in the include/corvusoft/restbed directory (rel is my installation directory, set using cmake):

![image](https://cloud.githubusercontent.com/assets/16206628/16763441/19ccd43c-4829-11e6-9874-47a048633ac3.png)

The detail directory is missing. As a result, when I compile my program, it fails as explained earlier. The following line `#include <corvusoft/restbed/detail/common_impl.hpp>` in [here](https://github.com/Corvusoft/restbed/blob/07bc5d0bc403800066b88c5ba3fa28907e688960/source/corvusoft/restbed/request.hpp#L18) broke the compilation of my program since the detail directory does not exist.

The source directory has the detail directory included:
![image](https://cloud.githubusercontent.com/assets/16206628/16763626/f2493b2a-4829-11e6-8e2f-7bae713ba4b9.png)

Are some files failing to move when I do `make install`?

**Comment by ben-crowhurst** [comment] 2016-07-12 17:12
Sorry about that @kvnnap we are mid refactor.  If you the pull latest this issue has been resolved.

**Comment by ben-crowhurst** [comment] 2016-07-12 17:16
Ah! Thank you for highlighting the miss understanding with synchronous [Http::fetch](https://github.com/Corvusoft/restbed/blob/master/example/http_client/source/example.cpp#L33) and asynchronous Session::fetch; very confusing.  I shall refactor these methods to give a more consistent interface.

**Comment by ben-crowhurst** [comment] 2016-08-11 19:58
Has anyone been able to confirm this fix?

**Closed** 2016-09-20 22:35 UTC
Labels: help wanted
