### ISSUE TITLE
Restbed 4.7 is changing HTTPS GET to HTTP GET

### ISSUE THREAD

**Issue by rayyar** [Corvusoft/restbed#421] opened 2020-04-23 16:42 UTC
Restbed request for GET command with
auto request = std::make_shared<restbed::Request>(restbed::Uri(getUri));

The getUri scheme contains HTTP. The request going out from Restbed changes HTTPS to HTTP.

**Comment by rayyar** [comment] 2020-04-23 18:21
As an example, modified code to set the query for https://github.com/settings/admin
but Rest bed sent out http://github.com/settings/admin

See attached pcap, packet 1995.


[restbedHttps.pcap.zip](https://github.com/Corvusoft/restbed/files/4524459/restbedHttps.pcap.zip)

**Comment by rayyar** [comment] 2020-04-29 13:28
Any update on this issue? Any other information needed to  assist in investigation?
Thanks

**Comment by ben-crowhurst** [comment] 2021-05-13 00:40
@rayyar did you manage to root cause your issue?

**Comment by ben-crowhurst** [comment] 2021-06-08 03:52
@rayyar if you could provide a clear picture of the problem perhaps with a complete code example.  We've attempted to duplicate based on the supplied information.  Please feel free to reopen this issue with additional information attached.

Closing as insufficient information given.

**Closed by ben-crowhurst** 2021-06-08 03:52 UTC
Labels: help wanted
