### ISSUE TITLE
Just after clone and try buid I got date_impl.cpp:78:66: error: ‘put_time’ was not declared

### ISSUE THREAD

**Issue by mingodad** [Corvusoft/restbed#1] opened 2015-06-21 16:36 UTC
restbed/dependency/framework/source/corvusoft/framework/detail/date_impl.cpp:78:66: error: ‘put_time’ was not declared in this scope

**Comment by ben-crowhurst** [comment] 2015-06-21 16:44
Please provide compiler information.  I think you'll be seeing the following issue.

http://stackoverflow.com/questions/14136833/stdput-time-implementation-status-in-gcc

**Comment by ben-crowhurst** [comment] 2015-06-22 18:23
@mingodad Was this the cause of your dilemma?

**Comment by ben-crowhurst** [comment] 2015-06-25 07:52
Closing as OP unresponsive.

**Closed by ben-crowhurst** 2015-06-25 07:52 UTC
Labels: help wanted

**Comment by ben-crowhurst** [comment] 2015-07-25 05:29
Framework as been collapsed into the core product. This should help resolve many build issues.
